### ISSUE TITLE
How to test database interactions 

### ISSUE THREAD

**Issue by infprime** [scottescue/dropwizard-entitymanager#38]
@scottescue 
Do you have any pointers on how the database interactions can be tested?

**Comment by scottescue** [comment]
I generally only test the database interactions in my integration/end-to-end tests. When I'm able to do that, I have the integration test fire up a light-weight database, run the application's Liquibase migrations, and seed any data needed for the test methods.  All that happens once per class.  Then the test methods use a REST client to test interactions with resource methods, which in turn trigger actual interactions with the database.

I have a dropwizard-entitymanager-example project that includes an example of such an integration test. But I haven't gotten around to polishing it up and publishing it. I'll try to find some time to get it pushed out in the next day or so.

**Comment by infprime** [comment]
I wanted to see if there was any way other than using full stack tests to invoke the Dao. I can make do with this approach for now.
